### ISSUE TITLE
Unusable - Safe Mode with default settings on ios 15.1

### ISSUE THREAD

**Issue by Computahwiz-Github** [neoighodaro/switcher-issues#11]
i can provide a crash log if someone tells me where that would be stored. I purchased jumper a while ago back on ios 14 and it was great. Went to get it again on Dopamine, and it sends me to safe mode regardless of what settings I set.

**Comment by HubertsProjects** [comment]
I have the same issue on my iPhone 12 Pro Max iOS 15.0.2.

However this does not occur on my iPhone 13 pro max on iOS 15.3.1

Crash log for the iPhone 12 below: 

![image](https://github.com/neoighodaro/switcher-issues/assets/60948875/b2a62020-d2ee-4e3d-a26b-3fefc7c7ba0d)

**Comment by neoighodaro** [comment]
Hey thanks for reporting, since for now its not in active development, IF you purchased Jumper recently, please send me your Havoc order ID [portion.influx-0j@icloud.com](mailto:portion.influx-0j@icloud.com), I'll send you a refund. If its not a recent purchase, I may not be able to do anything about it for now. However, when I can get a jb device again I could look into fixing it and send an update.
