### ISSUE TITLE
Icons are offset

### ISSUE THREAD

**Issue by laki2525** [neoighodaro/switcher-issues#13]
As you can see on the screenshot, when I expand menu, shortcuts are a little bit offset.
I am using iPhone SE first gen, ios 15.8.2, Dopamine jailbreak
![IMG_20240623_010352_412](https://github.com/neoighodaro/switcher-issues/assets/94998835/a2998607-9287-4cdf-8162-93553b2a6f7b)

**Comment by neoighodaro** [comment]
Hey thanks for reporting, since for now its not in active development, IF you purchased Jumper recently, please send me your Havoc order ID [portion.influx-0j@icloud.com](mailto:portion.influx-0j@icloud.com), I'll send you a refund. If its not a recent purchase, I may not be able to do anything about it for now.
